#!/bin/bash

commitMessage=$(cat $1)

#([^-]*-[^-]*)-.*
pattern="([A-z]{1,5}-[0-9]{1,})+"
if [[ ! "$commitMessag" =~ $pattern  ]]; then
	echo "Please add an issue number to the commit message: $commitMessage"
	exit 1
fi